//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_dyplomowa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Id { get; set; }
        public string Imie_wlasciciela { get; set; }
        public string Nazwisko_wlasciciela { get; set; }
        public string Numer_telefonu { get; set; }
        public string Aders { get; set; }
    }
}
