//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_dyplomowa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storeroom
    {
        public int Id { get; set; }
        public string Nazwa_leku { get; set; }
        public Nullable<System.DateTime> Data_waznosci { get; set; }
        public string Ilosc { get; set; }
    }
}
